name: GitHub Actions Demo
on: [push]
jobs:
  Set-Up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: go get
        run: go get github.com/gocolly/colly
        working-directory: ${{ github.workspace }}/cf-problems-backend
      - name: go build
        run: go build -o main *.go
        working-directory: ${{ github.workspace }}/cf-problems-backend
      - name: run go binary
        run: ./main
        working-directory: ${{ github.workspace }}/cf-problems-backend
      - name: git setting
        run: |
          git config --local user.email "kira924age@gmail.com"
          git config --local user.name "kira924age"
      - name: Commit files
        run: |
          git add -A
          git commit -a -m "Update contest.json (By GitHub Actions)"
          git pull
          git push

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

